#91 Signup時に空文字を弾くvalidationをFEに追加
nostaygr/ranker pull request #121
Opened 2018-02-17 16:15 UTC by aikiyy

#91 をFEで実装する場合ということで、思い浮かんだやつを実装しました。

・空文字を弾くvalidationだけ実装
・stateを持たない方法を思いつかなかった
・format checkとかは、validate()の中に書くか、関数作っちゃうかで拡張するイメージ

@longtime1116 レビューお願いしますー

2018-02-18 10:19 UTC, longtime1116 commented
ちょっと知識不足のせいかさっぱり実装がわかっていないので、時間を下さい〜

2018-02-20 00:17 UTC, longtime1116 requested changes
コメントしました。
それぞれ対応するのかしないのかと、質問に対しては返事お願いします〜〜〜

2018-02-20 00:17 UTC, longtime1116 commented on frontend/src/Signup.jsx
> +    if(this.validate(name, email, password)) {
一般に、「validate メソッドが true を返す == バリデーションに引っかからなかった」なので、true/false になる場合が逆かな。

2018-02-20 00:17 UTC, longtime1116 commented on frontend/src/Signup.jsx
> +    return false
```
return validationError;
```
でいける。

(下の方で指摘したことも合わせて考えて、)
isValid とかの変数名にして、↓のように書いてしまうのがよいと思う。

```
return isValid;
```

2018-02-20 00:17 UTC, longtime1116 commented on .gitignore
> +.env
お、これいれちゃったんすね〜〜
ずっと目障りだったから良かった。

2018-02-20 00:17 UTC, longtime1116 commented on frontend/src/Signup.jsx
> +      eval("this.setState({" + event.target.name + "ErrorText: '', })");
[Q]
ここでeval使う理由がなんなのかわからなかった・・・？おしえてくれい。

2018-02-20 00:17 UTC, longtime1116 commented on frontend/src/Signup.jsx
> +  validate(name, email, password) {
1. このメソッドに引数として連想配列を渡して、
2. 連想配列をforEachして
validation するのはどう？

そうすると field とかいらなくなるし、eval(f) とか使わなくて済む。

呼び出し元は、

```
this.validate({name: name, email: email, password: password})
```

でいけるんだけど、keyとvalueで同じもの?を指定しているときは、以下のようにかけるのでこっちがよい

```
this.validate({name, email, password})
```

2018-02-20 00:17 UTC, longtime1116 commented on frontend/src/Signup.jsx
> +        eval("this.setState({" + f + "ErrorText: f + ' is invalid', })");
なにがどこで展開されるのかわかりづいらいので、もうちょいわかりやすくしてほしい。。

あと↑と同じくここで eval が必要な理由を教えて下さい！

文字列の中で変数を展開する方法は、全体的に↓の書き方を採用しているはずなので、こちらを使っていただけると！

```js
const hoge = "aaa"
str = `hoge is ${hoge}`
```

2018-02-21 14:55 UTC, aikiyy commented on frontend/src/Signup.jsx
> +    if(this.validate(name, email, password)) {
thx

2018-02-21 14:56 UTC, aikiyy commented on frontend/src/Signup.jsx
> +      eval("this.setState({" + event.target.name + "ErrorText: '', })");
このmethod名は、複数の項目で使い回すので、項目名に合わせた変数をいじりたい

2018-02-21 15:01 UTC, aikiyy commented on frontend/src/Signup.jsx
> +  validate(name, email, password) {
> ・format checkとかは、validate()の中に書くか
これをどうするか決めてなかったから、汎用的なメソッド書けなかったのよね。
別メソッド作成するってことで上記実装します

2018-02-21 15:03 UTC, aikiyy commented on frontend/src/Signup.jsx
> +        eval("this.setState({" + f + "ErrorText: f + ' is invalid', })");
evalを使っている理由は、変数名を動的にセットしなくちゃいけないから。
いい案があったら、教えてほしい

2018-02-21 15:08 UTC, aikiyy commented on frontend/src/Signup.jsx
> +  validate(name, email, password) {
あ、中でfor回してるのか、忘れてた

2018-02-21 15:13 UTC, aikiyy commented on frontend/src/Signup.jsx
> +  validate(name, email, password) {
これリストじゃなくて、連想配列な理由ってなんでしょう？

2018-02-22 02:27 UTC, longtime1116 reviewed
コメント返しました！

2018-02-22 02:27 UTC, longtime1116 commented on frontend/src/Signup.jsx
> +  validate(name, email, password) {
ユーザが直接入力した name, email, password が value で、key は field っていう変数で表されているやつ。
その対応をそのまま形にして渡すのが意味的にもきれいだし処理的にもきれいになるのでは？というかんじ。

2018-02-22 02:27 UTC, longtime1116 commented on frontend/src/Signup.jsx
> +        eval("this.setState({" + f + "ErrorText: f + ' is invalid', })");
連想配列で渡されていれば、↓みたいな感じでいけるとおもう。

```js
validate(obj) {
Object.keys(obj).forEach(key => {
    this.setState(`#{key}ErrorText: #{obj[key] is invalid.}`)
})
```

2018-02-22 02:27 UTC, longtime1116 commented on frontend/src/Signup.jsx
> +      eval("this.setState({" + event.target.name + "ErrorText: '', })");
よくわかっていないんだけど、↓じゃなんでいけないんだろう？変数の展開はしてくれるのでは？とおもってしまったんだけど。

```

this.setState({`#{event.target.name}ErrorText: ''`})
```

2018-02-22 02:31 UTC, longtime1116 commented on frontend/src/Signup.jsx
> +      eval("this.setState({" + event.target.name + "ErrorText: '', })");
あ、なんとなくわかったかも。
https://qiita.com/kmagai/items/95481a3b9fd97e4616c9
これでいけない？？

2018-02-25 04:46 UTC, aikiyy commented
eval使わなくても余裕でsetできました。あざます(_ _)

2018-02-27 00:14 UTC, longtime1116 commented on frontend/src/Signup.jsx
> +      // 空白チェック
これってTODOってこと？それとも処理内容？
空白っていうのは空文字列？それともホワイトスペースが入力されたとき？
そこら辺が明確なコメントにしてほしい！
(処理内容を示すならおそらくコメント無しで良い気がしている)

2018-02-27 00:14 UTC, longtime1116 commented on frontend/src/Signup.jsx
> +          [item + "ErrorText"]: `${item} is invalid`,
good!!!

2018-02-27 00:14 UTC, longtime1116 commented on frontend/src/Signup.jsx
> +      // 空白チェック
これってTODOってこと？それとも処理内容？
空白っていうのは空文字列？それともホワイトスペースが入力されたとき？
そこら辺が明確なコメントにしてほしい！
(処理内容を示すならおそらくコメント無しで良い気がしている)

2018-02-27 14:04 UTC, aikiyy commented
コメントで言われたの全部対応したんで、まとめますねー

- 対応した：validateのboolean返り値のtrue/falseを入れ替える
- 対応した：validateに連想配列で渡す
- 対応した：動的変数定義にevalを使わない
- 対応した：不要コメント消す

2018-02-28 08:52 UTC, longtime1116 commented
LGTM!

2018-02-28 08:52 UTC, longtime1116 approved these changes

2018-02-28 13:32 UTC, aikiyy commented
あざます！

2018-02-28 13:32 UTC, merged