#71 subjectの個別ページへのリンクを張る
nostaygr/ranker pull request #87
Opened 2018-01-11 12:56 UTC by aikiyy

#71 の件です。
一応個別subjectページ作成したけど、id載せるだけなので、issueとは紐付けないことにします。
@longtime1116 レビューお願いしますー

2018-01-11 23:25 UTC, longtime1116 commented on frontend/src/Subject.jsx
> +    const id = this.props.match.params.id
これで path の :id をとれるのか。こんな書き方があるんやな。

2018-01-11 23:27 UTC, longtime1116 requested changes
コメントしました。確認お願いします！

2018-01-11 23:27 UTC, longtime1116 commented on frontend/src/Subject.jsx
> +      <div>{id}</div>
id だけじゃなく、title も一応表示しておいて欲しいな。デバッグしやすいのと、いずれidいがいも表示するようになるしせっかくなので。

↓これのように、app.jsx のルート設定を変えておいてもらえると〜〜
https://qiita.com/nostrict/items/53a68156e444b9334a9e

2018-01-12 15:28 UTC, aikiyy commented on frontend/src/Subject.jsx
> +      <div>{id}</div>
理解不足なんだけど、簡単な実現方法がわからんわ 😓 
実装前に認識を合わせておきたいんだけど、ルートコンポーネントであるAppにstateを持たせることにして、それをSubjectに渡すって方法でおk？

2018-01-12 21:35 UTC, longtime1116 commented on frontend/src/Subject.jsx
> +      <div>{id}</div>
Subject は Subjects から呼び出されるので、Subjects コンポーネントから state で渡すはず。
で、react-router なところも変える。react-routerなところはインタフェースを書いてるみたいなノリかと。

ちがったらすんません！

react-router なところは、Subjects の onClick のときと同じような感じに鳴門思っている。(onClick という名前クソだな・・・すんません)

2018-01-12 22:09 UTC, longtime1116 commented on frontend/src/Subject.jsx
> +      <div>{id}</div>
Subjects は、コールバックをよびだして必要な情報を加工してSubject に渡して表示する役割ということ。

だから、title とかは Subjectsコンポーネントのstateに保持されるはず。

2018-01-12 22:09 UTC, longtime1116 commented on frontend/src/Subject.jsx
> +      <div>{id}</div>
Subjects は、コールバックをよびだして必要な情報を加工してSubject に渡して表示する役割ということ。

だから、title とかは Subjectsコンポーネントのstateに保持されるはず。

2018-01-12 22:10 UTC, longtime1116 commented on frontend/src/Subject.jsx
> +      <div>{id}</div>
Subjects は、コールバックをよびだして必要な情報を加工してSubject に渡して表示する役割ということ。

だから、title とかは Subjectsコンポーネントのstateに保持されるはず。

2018-01-13 03:15 UTC, aikiyy commented on frontend/src/Subject.jsx
> +      <div>{id}</div>
SubjectはSubjectsから呼び出しているわけではなくて、AppがSubjectsを、AppがSubjectを呼び出しいると思うんだよね。
SubjectsのLinkから引数渡せたらいいけど、調べても出てこないんだよねー

2018-01-14 04:09 UTC, longtime1116 commented on frontend/src/Subject.jsx
> +      <div>{id}</div>
ちょっと作業してみるわ。このブランチにコミットするかも。

2018-01-14 09:47 UTC, longtime1116 commented on frontend/src/Subject.jsx
> +    const { id, subject } = this.props;
一行でかける

2018-01-14 09:50 UTC, longtime1116 commented on frontend/src/app.jsx
> +                subject={this.findSubjectById(parseInt(props.match.params.id))}
ここで表示して欲しい subject を渡せるようにした。
Subject は渡されたものを表示するだけ。

2018-01-14 09:51 UTC, longtime1116 commented on frontend/src/Subjects.jsx
> +      this.props.showSubjects(localStorage.getItem('user_id'));
onClick では決して無かったので名前変えた。

2018-01-14 09:52 UTC, longtime1116 approved these changes

2018-01-14 09:52 UTC, longtime1116 commented
修正したので、レビューお願いします〜〜〜

2018-01-14 14:52 UTC, aikiyy commented
問題ないと思いますー

2018-01-14 23:33 UTC, merged